native set_user_knife_id(id, knifeId);

native set_user_knife(id, model[], submodel);
native set_user_butcher(id, model[], submodel);
native set_user_bayonet(id, model[], submodel);
native set_user_katana(id, model[], submodel);
native set_user_dagger(id, model[], submodel);
native set_user_usp(id, model[], submodel);
native set_user_player_skin(id, skin[]);

native toggle_user_knife(id);
native toggle_user_usp(id);