native set_user_knife_id(id, knifeId);

native set_default_knife(model[]);
native set_default_butcher(model[]);
native set_default_bayonet(model[]);
native set_default_katana(model[]);
native set_default_dagger(model[]);
native set_default_usp(model[]);

native set_user_knife(id, model[]);
native set_user_butcher(id, model[]);
native set_user_bayonet(id, model[]);
native set_user_katana(id, model[]);
native set_user_dagger(id, model[]);
native set_user_usp(id, model[]);
native set_user_player_skin(id, skin[]);

native toggle_user_knife(id);
native toggle_user_usp(id);